export const LOG_USER = 'LOG_USER'
export const SIGN_USER_IN = 'SIGN_USER_IN'
export const SIGN_USER_OUT = 'SIGN_USER_OUT'
export const LOG_OUT = 'LOG_OUT'
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS'